### ISSUE TITLE
Upgrade to godot 4?

### ISSUE THREAD

**Issue by TiagoGoddard** [gsioteam/godot-colyseus#4]
Is there a plan to upgrade to godot 4?

**Comment by gsioteam** [comment]
I tried the beta 4 but gived up. I faced many problem, such as: I can not use a constant script as class, can not access a subclass inside another file. And I have found a complete documentation. I think I should still waiting for a more complete version.

**Comment by AndreLeclercqOclock** [comment]
Hi 👋🏻 , thanks for your plugin 🙏🏻 . Any news about the upgrade ?!

**Comment by Maus3rSR** [comment]
Hello, here we are planning to use godot engine too :D

**Comment by gsioteam** [comment]
@AndreLeclercqOclock Check the 4.0 branch, it is already there.
