### ISSUE TITLE
Invalid call. Nonexistent function 'handshake' in base 'Nil'.

### ISSUE THREAD

**Issue by AndreLeclercqOclock** [gsioteam/godot-colyseus#5]
Hi 👋🏻 

I have a problem when I try to connect into my colyseus server (localhost).

## Versions
**Godot version : 4.1.1 - Stable**
**Colyseus Version : 0.15.0**
**Godot Colyseus : 0.1.0 - for Godot 4.0**

## Recreate the problem
- Create a basic Colyseus server with the command line `npm create colyseus-app@latest` and use the sample room "my_room".
- Create an autoload script "Colyseus" with the demo script "main.gd" into the addon files.
- Change the name of the room from "state_handler" to "my_room".
- Just start the game

## Error message

I don't have any errors or warning before start the game.

```
Invalid call. Nonexistent function 'handshake' in base 'Nil'.
0 - res://addons/godot_colyseus/lib/room.gd:101 - at function: _on_data
1 - res://addons/godot_colyseus/lib/room.gd:143 - at function: _on_frame
2 - res://addons/godot_colyseus/lib/frame_runner.gd:20 - at function: start
```

## Misc

On the server side, the connection works !

```
⚔️  Listening on http://localhost:2567
fetIuN3R5 joined!
fetIuN3R5 left!
room tkoJgZRQi disposing...
```

Thanks 🙏🏻

**Comment by gsioteam** [comment]
I see, looks like there are new handshake protocols.

**Comment by gsioteam** [comment]
Resolve at b541e03 for 4.0
